services:
  mysql:
    image: docker.m.daocloud.io/library/mysql:8.0

  redis:
    image: docker.m.daocloud.io/library/redis:6.2-alpine

  backend:
    build:
      args:
        MAVEN_IMAGE: docker.m.daocloud.io/library/maven:3.9.9-eclipse-temurin-17
        JRE_IMAGE: docker.m.daocloud.io/library/eclipse-temurin:17-jre

  nginx:
    image: docker.m.daocloud.io/library/nginx:1.27-alpine
