services:
  mysql:
    image: docker.m.daocloud.io/library/mysql:8.0

  redis:
    image: docker.m.daocloud.io/library/redis:6.2-alpine

  backend:
    build:
      args:
        MAVEN_IMAGE: docker.1ms.run/library/maven:3.9.11-eclipse-temurin-21
        JRE_IMAGE: docker.1ms.run/library/eclipse-temurin:21-jre

  agent-service:
    build:
      args:
        PYTHON_IMAGE: docker.1ms.run/library/python:3.12-slim

  nginx:
    image: docker.m.daocloud.io/library/nginx:1.27-alpine
